// Start with verbs because it's actions : )
export const FETCH_TAGS = 'FETCH_TAGS'
export const FETCH_ARTICLES = 'FETCH_ARTICLES'
export const START_FETCH_ARTICLES = 'START_FETCH_ARTICLES'
export const REGISTER_ACCOUNT = 'REGISTER_ACCOUNT'
export const LOGIN_ACCOUNT = 'LOGIN_ACCOUNT'
export const LOGOUT_ACCOUNT = 'LOGOUT_ACCOUNT'
export const CHECK_AUTH = 'CHECK_AUTH'
export const SET_ERROR = 'SET_ERROR'
export const FETCH_COMMENT = 'FETCH_COMMENT'
export const FETCH_ARTICLE = 'FETCH_ARTICLE'
export const FETCH_FEED_ARTICLES = 'FETCH_FEED_ARTICLES'
